name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Windows Build
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure
      run: |
        cmake -B build -DBUILD_SHARED_LIBS=TRUE
        
    - name: Build
      run: cmake --build build --config Release
